// Generated by gencpp from file intro_tutorial/robotserviceRequest.msg
// DO NOT EDIT!


#ifndef INTRO_TUTORIAL_MESSAGE_ROBOTSERVICEREQUEST_H
#define INTRO_TUTORIAL_MESSAGE_ROBOTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace intro_tutorial
{
template <class ContainerAllocator>
struct robotserviceRequest_
{
  typedef robotserviceRequest_<ContainerAllocator> Type;

  robotserviceRequest_()
    : header()
    , station_id(0)  {
    }
  robotserviceRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , station_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _station_id_type;
  _station_id_type station_id;





  typedef boost::shared_ptr< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robotserviceRequest_

typedef ::intro_tutorial::robotserviceRequest_<std::allocator<void> > robotserviceRequest;

typedef boost::shared_ptr< ::intro_tutorial::robotserviceRequest > robotserviceRequestPtr;
typedef boost::shared_ptr< ::intro_tutorial::robotserviceRequest const> robotserviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intro_tutorial::robotserviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intro_tutorial::robotserviceRequest_<ContainerAllocator1> & lhs, const ::intro_tutorial::robotserviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.station_id == rhs.station_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intro_tutorial::robotserviceRequest_<ContainerAllocator1> & lhs, const ::intro_tutorial::robotserviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intro_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fcc66061f1c95dcabea76fde157bf1f";
  }

  static const char* value(const ::intro_tutorial::robotserviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fcc66061f1c95dcULL;
  static const uint64_t static_value2 = 0xabea76fde157bf1fULL;
};

template<class ContainerAllocator>
struct DataType< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intro_tutorial/robotserviceRequest";
  }

  static const char* value(const ::intro_tutorial::robotserviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 station_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::intro_tutorial::robotserviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.station_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotserviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intro_tutorial::robotserviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intro_tutorial::robotserviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "station_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.station_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRO_TUTORIAL_MESSAGE_ROBOTSERVICEREQUEST_H
