// Generated by gencpp from file intro_tutorial/robotservice.msg
// DO NOT EDIT!


#ifndef INTRO_TUTORIAL_MESSAGE_ROBOTSERVICE_H
#define INTRO_TUTORIAL_MESSAGE_ROBOTSERVICE_H

#include <ros/service_traits.h>


#include <intro_tutorial/robotserviceRequest.h>
#include <intro_tutorial/robotserviceResponse.h>


namespace intro_tutorial
{

struct robotservice
{

typedef robotserviceRequest Request;
typedef robotserviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotservice
} // namespace intro_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intro_tutorial::robotservice > {
  static const char* value()
  {
    return "5e604e0f37596f59d351957b85cd7f37";
  }

  static const char* value(const ::intro_tutorial::robotservice&) { return value(); }
};

template<>
struct DataType< ::intro_tutorial::robotservice > {
  static const char* value()
  {
    return "intro_tutorial/robotservice";
  }

  static const char* value(const ::intro_tutorial::robotservice&) { return value(); }
};


// service_traits::MD5Sum< ::intro_tutorial::robotserviceRequest> should match
// service_traits::MD5Sum< ::intro_tutorial::robotservice >
template<>
struct MD5Sum< ::intro_tutorial::robotserviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intro_tutorial::robotservice >::value();
  }
  static const char* value(const ::intro_tutorial::robotserviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intro_tutorial::robotserviceRequest> should match
// service_traits::DataType< ::intro_tutorial::robotservice >
template<>
struct DataType< ::intro_tutorial::robotserviceRequest>
{
  static const char* value()
  {
    return DataType< ::intro_tutorial::robotservice >::value();
  }
  static const char* value(const ::intro_tutorial::robotserviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intro_tutorial::robotserviceResponse> should match
// service_traits::MD5Sum< ::intro_tutorial::robotservice >
template<>
struct MD5Sum< ::intro_tutorial::robotserviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intro_tutorial::robotservice >::value();
  }
  static const char* value(const ::intro_tutorial::robotserviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intro_tutorial::robotserviceResponse> should match
// service_traits::DataType< ::intro_tutorial::robotservice >
template<>
struct DataType< ::intro_tutorial::robotserviceResponse>
{
  static const char* value()
  {
    return DataType< ::intro_tutorial::robotservice >::value();
  }
  static const char* value(const ::intro_tutorial::robotserviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTRO_TUTORIAL_MESSAGE_ROBOTSERVICE_H
