// Generated by gencpp from file intro_tutorial/robotserviceResponse.msg
// DO NOT EDIT!


#ifndef INTRO_TUTORIAL_MESSAGE_ROBOTSERVICERESPONSE_H
#define INTRO_TUTORIAL_MESSAGE_ROBOTSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intro_tutorial
{
template <class ContainerAllocator>
struct robotserviceResponse_
{
  typedef robotserviceResponse_<ContainerAllocator> Type;

  robotserviceResponse_()
    : room_id(0)  {
    }
  robotserviceResponse_(const ContainerAllocator& _alloc)
    : room_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _room_id_type;
  _room_id_type room_id;





  typedef boost::shared_ptr< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotserviceResponse_

typedef ::intro_tutorial::robotserviceResponse_<std::allocator<void> > robotserviceResponse;

typedef boost::shared_ptr< ::intro_tutorial::robotserviceResponse > robotserviceResponsePtr;
typedef boost::shared_ptr< ::intro_tutorial::robotserviceResponse const> robotserviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intro_tutorial::robotserviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intro_tutorial::robotserviceResponse_<ContainerAllocator1> & lhs, const ::intro_tutorial::robotserviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.room_id == rhs.room_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intro_tutorial::robotserviceResponse_<ContainerAllocator1> & lhs, const ::intro_tutorial::robotserviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intro_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb9d79aabfdcaaabb6b9a15a2f03dd5b";
  }

  static const char* value(const ::intro_tutorial::robotserviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb9d79aabfdcaaabULL;
  static const uint64_t static_value2 = 0xb6b9a15a2f03dd5bULL;
};

template<class ContainerAllocator>
struct DataType< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intro_tutorial/robotserviceResponse";
  }

  static const char* value(const ::intro_tutorial::robotserviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 room_id\n"
"\n"
;
  }

  static const char* value(const ::intro_tutorial::robotserviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotserviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intro_tutorial::robotserviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intro_tutorial::robotserviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "room_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.room_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRO_TUTORIAL_MESSAGE_ROBOTSERVICERESPONSE_H
